/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `movieServer.movies`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `movies`;
CREATE TABLE `movies` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `movieDownload` LONGTEXT,
    `movieImg` LONGTEXT,
    `movieMainPage` BIT,
    `movieName` LONGTEXT,
    `movieNumDownload` INTEGER,
    `movieNumSuppose` INTEGER,
    `movieTime` LONGTEXT,
    `movieVideo` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D09BB49B831750D82886CE5', 'https://www.iqiyi.com/v_19rr8ya20o.html', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1562675565641&di=7b170c5348b2083d5f75334edb2605d9&imgtype=0&src=http%3A%2F%2Fi1.wp.com%2Fimg.char.tw%2Fuploads%2F20181025172743_28.jpg%3Fresize%3D1600%2C905', FALSE, '追龙', 3276, 123, '2019-06-19', 'https://movie.douban.com/trailer/221961/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D09E93CDFB8DC3494D4501E', 'https://www.iqiyi.com/v_19rrfe142o.html', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1561381917376&di=fa554b8ff198ebff910afb548dd5b50f&imgtype=0&src=http%3A%2F%2Fi1.hdslb.com%2Fbfs%2Farchive%2F095e7b89daf78e084d452e11f1695fb821eda0ab.jpg', TRUE, '流浪地球', 5767, 1209, '2019-02-05', 'https://movie.douban.com/video/102604/');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D09E9D3DFB8DC3494D45020', 'https://www.douban.com/link2/?url=http%3A%2F%2Fwww.iqiyi.com%2Fv_19rqycwafc.html%3Fvfm%3Dm_331_dbdy%26fv%3D4904d94982104144a1548dd9040df241&subtype=9&type=online-video', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1562675635155&di=f335823bbf1008f8f7feac7ddcd71da3&imgtype=0&src=http%3A%2F%2Fi0.hdslb.com%2Fbfs%2Farticle%2Ffd0dd653bec8c800c62d3e219dd3eaf512018d6b.jpg', FALSE, '波西米亚狂想曲 Bohemian Rhapsody', 187, 207, '2019-03-22', 'https://movie.douban.com/trailer/233799/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D10A45D7F0A541B8D9B3A9E', 'https://www.douban.com/link2/?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMzA1NTAzNjAwMA%3D%3D.html%3Ftpa%3DdW5pb25faWQ9MzAwMDA4XzEwMDAwMl8wMl8wMQ%26refer%3Ddoubanneirongshuchu_bd.xuyang01_douban_201122&subtype=3&type=online-video', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1561381801142&di=515c7439d7a1a40be7587cad291b1b91&imgtype=0&src=http%3A%2F%2Fwww.fjsen.com%2Fimages%2Fattachement%2Fjpg%2Fsite1%2F2011-05-24%2F7775612759867346311.jpg', FALSE, '霸王别姬', 559, 1057, '1993-01-01', 'https://movie.douban.com/trailer/239810/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D122049518FC462F4D6B379', 'https://www.douban.com/link2/?url=https%3A%2F%2Fwww.bilibili.com%2Fbangumi%2Fplay%2Fss10945%3Fbsource%3Ddouban&subtype=8&type=online-video&link2key=8ff2af5937', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1562675691797&di=2dfa4fdd44f0d9d9ef29c1057e4dfa4f&imgtype=0&src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2Ff5a2b2bfde0775a727615963e2387d50d1f4e5b53c5c3-O5cdIq_fw658', FALSE, '这个杀手不太冷 Léon (1994)', 240, 589, '1994-09-14', 'https://movie.douban.com/trailer/108757/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D122093518FC462F4D6B38D', 'https://www.douban.com/link2/?url=http%3A%2F%2Fv.qq.com%2Fx%2Fcover%2Fr6hc2kqgvnmiejn.html%3Fptag%3Ddouban.movie&subtype=1&type=online-video', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1562675775405&di=a24753f4a0bdba7f46080830c6890a18&imgtype=0&src=http%3A%2F%2Fimg0.pconline.com.cn%2Fpconline%2F1205%2F07%2F2777169_13_thumb.jpg', FALSE, '阿甘正传 Forrest Gump (1994)', 67, 1246, '1994-06-23', 'https://movie.douban.com/trailer/160000/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D12209B518FC462F4D6B38E', 'https://www.douban.com/link2/?url=http%3A%2F%2Fwww.iqiyi.com%2Fv_19rrjqfdbc.html%3Fvfm%3Dm_331_dbdy%26fv%3D4904d94982104144a1548dd9040df241&subtype=9&type=online-video', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1563270529&di=57e1613dcc9fd4c2a1d720e3ee9106c2&imgtype=jpg&er=1&src=http%3A%2F%2Fimg1.doubanio.com%2Fview%2Fnote%2Flarge%2Fpublic%2Fp39919097.jpg', FALSE, '美丽人生 La vita è bella (1997)', 234, 5189, '1997-12-20', 'https://movie.douban.com/trailer/108759/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D1220AA518FC462F4D6B39E', 'https://www.douban.com/link2/?url=http%3A%2F%2Fv.qq.com%2Fx%2Fcover%2Ft5jqhgw8pix81mw.html%3Fptag%3Ddouban.movie&subtype=1&type=online-video', 'https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=4236395672,1233225696&fm=26&gp=0.jpg', FALSE, '泰坦尼克号 Titanic (1997)', 1167, 4567, '1998-04-03', 'https://movie.douban.com/trailer/112229/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D1221B1518FC462F4D6B3E0', 'https://movie.douban.com/ticket/redirect/?url=https%3A%2F%2Fm.maoyan.com%2Fcinema%2Fmovie%2F246264%3F_v_%3Dyes%26merCode%3D1000011', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2557284230.webp', TRUE, '玩具总动员4 Toy Story 4 (2019)', 34, 345, '2019-06-21', 'https://movie.douban.com/trailer/247424/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D1221B4518FC462F4D6B3E1', 'https://movie.douban.com/ticket/redirect/?url=https%3A%2F%2Fm.maoyan.com%2Fcinema%2Fmovie%2F246061%3F_v_%3Dyes%26merCode%3D1000011', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2554370800.webp', TRUE, '哥斯拉2：怪兽之王 Godzilla: King of the Monsters (2019)', 681, 135, '2019-05-31', 'https://movie.douban.com/trailer/246166/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (NULL, x'5D1221B6518FC462F4D6B3E2', 'https://movie.douban.com/ticket/redirect/?url=https%3A%2F%2Fm.maoyan.com%2Fcinema%2Fmovie%2F1226516%3F_v_%3Dyes%26merCode%3D1000011', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2557500825.webp', TRUE, '哆啦A梦：大雄的月球探险记 映画ドラえもん のび太の月面探査記 (2019)', 126, 800, '2019-06-01 ', 'https://movie.douban.com/trailer/247560/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D1372C751F4D5138CB519F9', 'https://www.douban.com/link2/?url=https%3A%2F%2Fv.qq.com%2Fx%2Fcover%2F120m3xjxyr69vlz%2Fw0030ma4dhv.html&subtype=1&type=online-video', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2551995207.webp', FALSE, '调音师 Andhadhun (2018)', 115, 1214, '2019-04-03', 'https://movie.douban.com/trailer/244969/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D1376312C785A0EE8544818', 'https://movie.douban.com/ticket/redirect/?url=https%3A%2F%2Fm.maoyan.com%2Fcinema%2Fmovie%2F346629%3F_v_%3Dyes%26merCode%3D1000011', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2555538168.webp', FALSE, '大侦探皮卡丘 Pokémon Detective Pikachu (2019)', 112, 913, '2019-05-10', 'https://movie.douban.com/trailer/243768/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D1376D281C3CA3338E69BA0', 'https://movie.douban.com/ticket/redirect/?url=https%3A%2F%2Fm.maoyan.com%2Fcinema%2Fmovie%2F346629%3F_v_%3Dyes%26merCode%3D1000011', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1562675893720&di=047a70b46a73271a7dc62046b8bd298c&imgtype=0&src=http%3A%2F%2Fi2.hexun.com%2F2019-02-14%2F196132192.jpg', FALSE, '阿丽塔：战斗天使 Alita: Battle Angel (2019)', 123, 96, '2019-02-22', 'https://movie.douban.com/trailer/241829/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D22CB60DDC37A0570118BD4', 'https://movie.douban.com/ticket/redirect/?url=https%3A%2F%2Fm.maoyan.com%2Fcinema%2Fmovie%2F1198925%3F_v_%3Dyes%26merCode%3D1000011', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2558293106.webp', TRUE, '蜘蛛侠：英雄远征 Spider-Man: Far From Home (2019)', 116, 168, '2019-06-28', 'https://movie.douban.com/trailer/248749/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D22CB79DDC37A0570118BD5', 'https://movie.douban.com/subject/30171425/?from=showing', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2561172733.webp', TRUE, '扫毒2天地对决 (2019)', 1121, 516, '2019-07-05', 'https://movie.douban.com/trailer/249286/#content');
INSERT INTO `movies` (`__v`, `_id`, `movieDownload`, `movieImg`, `movieMainPage`, `movieName`, `movieNumDownload`, `movieNumSuppose`, `movieTime`, `movieVideo`)
    VALUES
        (0, x'5D22CC145475453330A94B31', 'https://www.douban.com/link2/?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XNDAwNDUxMzUyOA%3D%3D.html%3Ftpa%3DdW5pb25faWQ9MzAwMDA4XzEwMDAwMl8wMl8wMQ%26refer%3Desfhz_operation.xuka.xj_00003036_000000_FNZfau_19010900&subtype=3&type=online-video', 'https://img3.doubanio.com/view/photo/l/public/p2537158013.webp', FALSE, '毒液：致命守护者 Venom (2018)', 121, 131, '2018-11-09', 'https://movie.douban.com/trailer/238802/#content');
