/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `movieServer.mails`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `mails`;
CREATE TABLE `mails` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `context` LONGTEXT,
    `date` LONGTEXT,
    `fromUser` LONGTEXT,
    `title` LONGTEXT,
    `toUser` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `mails` (`__v`, `_id`, `context`, `date`, `fromUser`, `title`, `toUser`)
    VALUES
        (0, x'5D09A3A7405D8131CC61DC8A', '站内信内容1', '2019-6-19 10:53:27 AM', '5d08883f78394b28d4b2c331', '站内信标题1', '5d08990b8fadcc259091fd5e');
INSERT INTO `mails` (`__v`, `_id`, `context`, `date`, `fromUser`, `title`, `toUser`)
    VALUES
        (0, x'5D09A3B1405D8131CC61DC8B', '站内信内容2', '2019-6-19 10:53:37 AM', '5d08883f78394b28d4b2c331', '站内信标题2', '5d08990b8fadcc259091fd5e');
INSERT INTO `mails` (`__v`, `_id`, `context`, `date`, `fromUser`, `title`, `toUser`)
    VALUES
        (0, x'5D09A3D7405D8131CC61DC8C', '站内信内容3', '2019-6-19 10:54:15 AM', '5d08883f78394b28d4b2c331', '站内信标题3', '5d08888e0fc324056011da74');
INSERT INTO `mails` (`__v`, `_id`, `context`, `date`, `fromUser`, `title`, `toUser`)
    VALUES
        (0, x'5D09A5D2405D8131CC61DC8D', '站内信内容4', '2019-6-19 11:02:42 AM', '5d08883f78394b28d4b2c331', '站内信标题4', '5d08883f78394b28d4b2c331');
