/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `movieServer.recommends`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `recommends`;
CREATE TABLE `recommends` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `recommendImg` LONGTEXT,
    `recommendSrc` LONGTEXT,
    `recommendTitle` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `recommends` (`__v`, `_id`, `recommendImg`, `recommendSrc`, `recommendTitle`)
    VALUES
        (0, x'5D121067518FC462F4D6B360', 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1561381917376&di=fa554b8ff198ebff910afb548dd5b50f&imgtype=0&src=http%3A%2F%2Fi1.hdslb.com%2Fbfs%2Farchive%2F095e7b89daf78e084d452e11f1695fb821eda0ab.jpg', 'https://www.iqiyi.com/v_19rrfe142o.html', '流浪地球');
