/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `movieServer.comments`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `check` BIT,
    `context` LONGTEXT,
    `movie_id` LONGTEXT,
    `username` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D0897E03364A61D1C8C0621', TRUE, 'zhenhaokan', '5d09e9d3dfb8dc3494d45020', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D08985D548F9400CC3B699A', FALSE, 'zhenhaokan', '5d09e9d3dfb8dc3494d45020', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D103B13C4984F1F68E08839', FALSE, '评论测试', '5d09e93cdfb8dc3494d4501e', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10404699302109A07C4B6E', TRUE, '牛逼！！！好音乐真是颗幸福的原子弹！', '5d09e9d3dfb8dc3494d45020', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10405099302109A07C4B6F', TRUE, '这是我今年最喜欢的电影，没有之一。', '5d09e9d3dfb8dc3494d45020', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10425299302109A07C4B71', TRUE, '雷洛加跛豪，王晶这回没有玩贱而是难得严肃了一回，整体制作非常老港片的味道，老派枭雄电影的感觉。刘德华果然是越来越有型了。', '5d09bb49b831750d82886ce5', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D1043C999302109A07C4B72', TRUE, '王晶开辟了一个新类型——民族主义黑帮片。此片可作为新世纪后殖民主义港片的代表作，与具有分裂倾向的港毒片近身肉搏。', '5d09bb49b831750d82886ce5', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10448F99302109A07C4B73', FALSE, '江湖鱼龙混杂，如今尽是鱼虾。龙已飞天而去，任尔泥沙俱下。', '5d09bb49b831750d82886ce5', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D104A164B22CE100847E887', TRUE, '黄渤是有追求的导演，之前真没敢报期望。中国式反乌托邦，以为会是麻花式的喜剧，会在老本行上偷懒，但远远挖掘了更深层次的东西，这对于处女作来说实属不易。体制内无法呈现的阴暗面，以巧妙的抉择呈现，效果惊艳。美术、音乐以及表演掌控自如，恭喜黄渤！', '5d09c057b831750d82886d3b', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D104A264B22CE100847E888', TRUE, '真·一出好戏。剧情表演俱佳，求生模式的暗黑剧情扣人心弦，群戏表演很见功力。最意外张艺兴表演，黑化得很酷了；舒淇一如既往美如画。船舱倒立视角印象深刻，表现力和寓言性十足', '5d09c057b831750d82886d3b', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10A0AFDC89001D9C6986A1', TRUE, '犹记得当年看雷洛传，王晶不拍贺岁尬喜剧的时候，成熟的功底，配乐就凸现了。甚至还玩起了长镜头。主角配角皆有演技，真的是太久太久没见这样纯正怀旧的港片了。', '5d09bb49b831750d82886ce5', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10A0E8DC89001D9C6986A2', TRUE, '神！最后一场戏，基本还原了当年皇后乐队在live aid演唱会的盛况，曲目百分之八十保留，还有龅牙叔献给母亲的那个吻。', '5d09e9d3dfb8dc3494d45020', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10A112DC89001D9C6986A3', TRUE, '当熟悉的音符如电流般直抵高潮，纯粹的角色塑造显得无足轻重，对你，摇滚传奇Freddie Mercury而言，再没有比歌声更精确的人格注脚了。 一成不变的天空，偶尔会有燃烧的陨星击穿云层，即兴地闪耀，清脆地焚毁，散成光艳袭人的碎片，巡游在历史里，巡游在半空，被人呼吸，被不同的时代回忆。', '5d0a1b9414cd341520ce1885', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10A138DC89001D9C6986A4', TRUE, '“如果再也不能见到你，祝你早安，午安和晚安。”', '5d09c102b831750d82886d46', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D10E8B5E00958339483960B', TRUE, '666', '5d09e93cdfb8dc3494d4501e', 'yjp');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D11A7A57CAF172090B85919', TRUE, 'yjp', '5d09e9d3dfb8dc3494d45020', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D122D4F7B666626C08A9A80', TRUE, '真好看！看的热血沸腾！', '5d09e9d3dfb8dc3494d45020', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D12EF2DC7A167206070256F', TRUE, '打开这道门，即便现实再最肮脏也请让我自己感受！关掉你的镜头，即使现实再无奈你也必须自己体验！', '5d09c102b831750d82886d46', 'wj');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D12F01AC7A1672060702571', TRUE, '荒诞中揭示人性，导演处女作应该说太用心了，简直就是想费力而不只是想讨好(巧)观众；场景和特效都非常认真，荒岛，破船的造型……电影就是高度文明的人再退回到猴子原始时代的现代寓言，这也足见一个酝酿多年的演而优则导的处女作的良苦『野心』，如果多一些这样的的导演，那么我们的国产電影好看了', '5d09c057b831750d82886d3b', 'test');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D12F0D1C7A1672060702575', TRUE, '666', '5d0a1b9414cd341520ce1885', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D138F896491AB2EA0F80EFA', TRUE, '666', '5d12eaa582f1d1537b57e3f2', '匿名用户');
INSERT INTO `comments` (`__v`, `_id`, `check`, `context`, `movie_id`, `username`)
    VALUES
        (0, x'5D24610B33B1F42C9C1DE628', TRUE, '国产科幻巨作！', '5d09e93cdfb8dc3494d4501e', 'wj');
